version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=20"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      bugsnag:
        patterns:
          - "@bugsnag/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
