name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
  - title: '⚙️ Dependencies'
      labels:
        - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
category-template: |
  ## $TITLE
template: |
  ## Changes 

  $CHANGES
  
  ---
footer: |
  [Detailed comparison](https://github.com/ZigaStrgar/fastify-bugsnag/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) between [$PREVIOUS_TAG](https://github.com/ZigaStrgar/fastify-bugsnag/releases/tag/$PREVIOUS_TAG) and [$RESOLVED_VERSION](https://github.com/ZigaStrgar/fastify-bugsnag/releases/tag/$RESOLVED_VERSION).
