name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes - 

  $CHANGES
footer: |
  [Detailed comparison]($REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) between [$PREVIOUS_TAG]($REPOSITORY/releases/tag/$PREVIOUS_TAG) and [$RESOLVED_VERSION]($REPOSITORY/releases/tag/$RESOLVED_VERSION).
